### ISSUE TITLE
Sort out docs by query type

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/cpan-api#348]
Please review / sort out #317 and resubmit

**Comment by andk** [comment]
I think a few things should disappear from the website.

The current text on https://github.com/CPAN-API/cpan-api/wiki/Beta-api-docs is not helpful. I paste it here. let me know if you do not understand why I find in not helpful.

*Beta api docs johnhomes edited this page on Jun 22 · 4 revisions The API docs are no longer in Beta and can be found The contents of this page have been moved into the repo and are being reorganized #316. (Page left because it's linked to quite a bit) Meanwhile, empower your life at bearpartners.*

The current text on https://github.com/CPAN-API/cpan-api/wiki/API-docs ... Same as above.

*API docs ranguard edited this page on Oct 29, 2014 · 29 revisions NOTE: Under Construction The contents of this page have been moved into the repo and are being reorganized #316.*

Note that both pages link to ticket 316 which is closed. It probably would do to have each page link to something useful?

**Comment by ranguard** [comment]
@andk thanks for the heads up - I've done a quick clean up - let me know if I missed anything, I've also closed the wiki to public edits

@rwstauner is this ticket actually done now the docs are merged?

Leo

**Comment by rwstauner** [comment]
Not really, but I don't think there's a reason to keep this open.  There's always an opportunity for any project to clean up its docs.
