### ISSUE TITLE
Filter by module doesn't seem to work

### ISSUE THREAD

**Issue by altern8tif** [CPAN-API/cpan-api#426]
I've been trying to use the following endpoint to filter out results that return modules.  Unfortunately, it seems like it still returns results that don't have the `module` field.

```
http://api.metacpan.org/v0/module/_search?q=pluggable+status:latest&fields=abstract,module,date,status&filter={"exists":{"field":"module"}}
```

Is my syntax wrong or is this a bug?

*Pardon my ignorance – rather new to CPAN.

**Comment by rwstauner** [comment]
I'm not sure if you can mix querystring parameters with json (especially with our old version of ES),
or what the syntax is for putting filters in the querystring.
The other problem is that I don't believe the `exists` filter works on an object, i think you need to specify a field with a value, so `module.name` instead of `module`.

This query worked for me:

```
curl -i -d '{"filter": {"exists": {"field": "file.module.name"}}}' 'http://api.metacpan.org/v0/module/_search?q=pluggable+status:latest&fields=abstract,module,date,status'
```
That returns 140091 hits compared to 1213167.

**Comment by altern8tif** [comment]
@rwstauner Thanks... It seems to work on MetaCPan Explorer too.  But is there a way to return that in a single URL endpoint instead?

I'm trying to integrate this into a [DuckDuckGo Instant Answer](https://github.com/duckduckgo/zeroclickinfo-spice/issues/898) and it's more complicated to have to use curl instead of just using a single API endpoint.

**Comment by ranguard** [comment]
Closing - hopefully when we upgrade to ES 2.2.0 this can be reviewed
